name: razinshop_rider
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.4.3+1
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  cupertino_icons: ^1.0.6
  pretty_dio_logger: ^1.3.1
  flutter_screenutil: ^5.9.0
  page_transition: ^2.1.0
  intl: ^0.18.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  image_picker: any
  pinput: ^4.0.0
  google_maps_flutter: any
  url_launcher: ^6.2.6
  calendar_date_picker2: ^0.5.5
  cached_network_image: ^3.3.1
  flutter_html: ^3.0.0-beta.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: any
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
        - asset: assets/fonts/Mulish-Bold.ttf


flutter_intl:
  enabled: true
